on:
  release:
    types:
      - published
  push:
    branches:
      - main
name: release

jobs:
  build-artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.26"
      - run: uv build
      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist/

  publish:
    name: Publish to PyPI
    needs: build-artifacts
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
